baseURL = 'http://example.org/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'enchanted-lowkey'
title = 'Shireen Chand'
enableRobotsTXT = true
summaryLength = 15
paginate = 5
googleAnalytics = "G-KR8P2WRM0C"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true